[package]
name = "opentok"
version = "1.0.0"
description = "Rust bindings for OpenTok SDK"
authors = ["Fernando Jimenez Moreno <fjimenez@igalia.com>"]
edition = "2018"

[dependencies]
ffi = { package = "opentok-rs-sys", path = "../../opentok-rs-sys" }
lazy_static = "1.4.0"
once_cell = "1.8.0"
thiserror = "1.0.24"

[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false
features = ["precommit-hook", "run-cargo-clippy"]
