[package]
name = "opentok-rs-sys"
version = "0.1.0"
description = "Rust FFI bindings for OpenTok SDK"
authors = ["Fernando Jimenez Moreno <fjimenez@igalia.com>"]
edition = "2018"
links = "opentok"
build = "build.rs"

[build-dependencies]
bindgen = "0.58.1"
